# Generated by Django 4.2.4 on 2024-09-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='uploads/blog_images/')),
                ('blog_content', models.TextField(max_length=1000)),
            ],
        ),
    ]
