# Generated by Django 4.2.4 on 2024-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=100, null=True)),
                ('blockchain', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('supply', models.IntegerField(blank=True, null=True)),
                ('private_mint_price', models.IntegerField(blank=True, null=True)),
                ('public_mint_price', models.IntegerField(blank=True, null=True)),
                ('private_mint_time', models.CharField(blank=True, max_length=20, null=True)),
                ('public_mint_time', models.CharField(blank=True, max_length=20, null=True)),
                ('public_mint_date', models.CharField(blank=True, max_length=20, null=True)),
                ('private_mint_date', models.CharField(blank=True, max_length=20, null=True)),
                ('verified', models.BooleanField(blank=True, default=True, null=True)),
                ('flagged', models.BooleanField(blank=True, default=False, null=True)),
                ('reported', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
