# Generated by Django 4.2.4 on 2024-09-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_info_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='info',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
