# Generated by Django 4.2.4 on 2024-09-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_info_background_image_info_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
