# Generated by Django 4.2.4 on 2024-09-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_info_paid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('nft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='info.info')),
            ],
        ),
    ]
