# Generated by Django 4.2.4 on 2024-09-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_voterip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='category',
            field=models.CharField(choices=[('free_mint', 'Free Mint'), ('pfp', 'PFP'), ('collectible', 'Collectible'), ('charity', 'Charity'), ('3d', '3D'), ('art', 'Art'), ('pixel', 'Pixel'), ('metaverse', 'Metaverse'), ('membership', 'Membership'), ('music', 'Music'), ('gaming', 'Gaming'), ('alpha', 'Alpha'), ('utility', 'Utility'), ('memecoin', 'Memecoin'), ('defi', 'Defi'), ('dex', 'Dex'), ('dao', 'Dao'), ('generative', 'Generative'), ('giveaway', 'Giveaway'), ('sports', 'Sports'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
