# Generated by Django 4.2.4 on 2024-09-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_info_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='private_mint_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='private_mint_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='public_mint_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='public_mint_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
