# Generated by Django 4.2.4 on 2024-09-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_info_private_mint_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='click_count',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
