# Generated by Django 4.2.4 on 2024-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_info_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='blockchain',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('solana', 'Solana'), ('polygon', 'Polygon'), ('avalanche', 'Avalanche'), ('aptos', 'Aptos'), ('cardano', 'Cardano'), ('near', 'Near'), ('sui', 'Sui'), ('algorand', 'Algorand'), ('multiversx', 'MultiversX'), ('arbitrum', 'Arbitrum'), ('sei', 'Sei'), ('binance', 'Binance'), ('cosmos', 'Cosmos'), ('hedera', 'Hedera'), ('venom', 'Venom'), ('icon', 'Icon'), ('immutable', 'Immutable'), ('injective', 'Injective'), ('ripple', 'Ripple'), ('dogecoin', 'Dogecoin'), ('base', 'Base'), ('wax', 'Wax'), ('flow', 'Flow'), ('reef', 'Reef'), ('internet_computer', 'Internet Computer'), ('starknet', 'StarkNet'), ('myria', 'Myria'), ('monad', 'Monad'), ('berachain', 'Berachain'), ('stargaze', 'Stargaze'), ('blast', 'Blast'), ('osmosis', 'Osmosis'), ('zksync', 'ZKSync'), ('enjin', 'Enjin'), ('linea', 'Linea'), ('skale_network', 'Skale Network'), ('ton', 'Ton'), ('oraichain', 'Oraichain')], default='Bitcoin', max_length=100),
        ),
    ]
